// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BasilMessage.proto

#include "BasilMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_BasilMessage_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_BasilMessage_OpParametersEntry_DoNotUse_BasilMessage_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_BasilMessage_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_BasilMessage_PropertiesEntry_DoNotUse_BasilMessage_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_BasilTypes_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_AaBoundingBox_BasilTypes_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_BasilTypes_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_AccessAuthorization_BasilTypes_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_BasilTypes_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_AssetInformation_BasilTypes_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_BasilTypes_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_BResponseRequest_BasilTypes_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_BasilTypes_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_BasilException_BasilTypes_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_BasilTypes_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_InstanceIdentifier_BasilTypes_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_BasilTypes_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<4> scc_info_InstancePositionInfo_BasilTypes_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_BasilTypes_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ObjectIdentifier_BasilTypes_2eproto;
namespace BasilMessage {
class BasilMessage_PropertiesEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<BasilMessage_PropertiesEntry_DoNotUse> _instance;
} _BasilMessage_PropertiesEntry_DoNotUse_default_instance_;
class BasilMessage_OpParametersEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<BasilMessage_OpParametersEntry_DoNotUse> _instance;
} _BasilMessage_OpParametersEntry_DoNotUse_default_instance_;
class BasilMessageDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<BasilMessage> _instance;
} _BasilMessage_default_instance_;
}  // namespace BasilMessage
static void InitDefaultsscc_info_BasilMessage_BasilMessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::BasilMessage::_BasilMessage_default_instance_;
    new (ptr) ::BasilMessage::BasilMessage();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::BasilMessage::BasilMessage::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<10> scc_info_BasilMessage_BasilMessage_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 10, InitDefaultsscc_info_BasilMessage_BasilMessage_2eproto}, {
      &scc_info_AccessAuthorization_BasilTypes_2eproto.base,
      &scc_info_ObjectIdentifier_BasilTypes_2eproto.base,
      &scc_info_InstanceIdentifier_BasilTypes_2eproto.base,
      &scc_info_InstancePositionInfo_BasilTypes_2eproto.base,
      &scc_info_AssetInformation_BasilTypes_2eproto.base,
      &scc_info_AaBoundingBox_BasilTypes_2eproto.base,
      &scc_info_BasilMessage_PropertiesEntry_DoNotUse_BasilMessage_2eproto.base,
      &scc_info_BasilMessage_OpParametersEntry_DoNotUse_BasilMessage_2eproto.base,
      &scc_info_BasilException_BasilTypes_2eproto.base,
      &scc_info_BResponseRequest_BasilTypes_2eproto.base,}};

static void InitDefaultsscc_info_BasilMessage_OpParametersEntry_DoNotUse_BasilMessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::BasilMessage::_BasilMessage_OpParametersEntry_DoNotUse_default_instance_;
    new (ptr) ::BasilMessage::BasilMessage_OpParametersEntry_DoNotUse();
  }
  ::BasilMessage::BasilMessage_OpParametersEntry_DoNotUse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_BasilMessage_OpParametersEntry_DoNotUse_BasilMessage_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_BasilMessage_OpParametersEntry_DoNotUse_BasilMessage_2eproto}, {}};

static void InitDefaultsscc_info_BasilMessage_PropertiesEntry_DoNotUse_BasilMessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::BasilMessage::_BasilMessage_PropertiesEntry_DoNotUse_default_instance_;
    new (ptr) ::BasilMessage::BasilMessage_PropertiesEntry_DoNotUse();
  }
  ::BasilMessage::BasilMessage_PropertiesEntry_DoNotUse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_BasilMessage_PropertiesEntry_DoNotUse_BasilMessage_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_BasilMessage_PropertiesEntry_DoNotUse_BasilMessage_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_BasilMessage_2eproto[3];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_BasilMessage_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_BasilMessage_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_BasilMessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage_PropertiesEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage_PropertiesEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage_PropertiesEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage_PropertiesEntry_DoNotUse, value_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage_OpParametersEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage_OpParametersEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage_OpParametersEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage_OpParametersEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage, op_),
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage, auth_),
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage, class__),
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage, objectid_),
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage, instanceid_),
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage, pos_),
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage, assetinfo_),
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage, aabb_),
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage, filter_),
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage, properties_),
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage, opparameters_),
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage, exception_),
  PROTOBUF_FIELD_OFFSET(::BasilMessage::BasilMessage, response_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::BasilMessage::BasilMessage_PropertiesEntry_DoNotUse)},
  { 9, 16, sizeof(::BasilMessage::BasilMessage_OpParametersEntry_DoNotUse)},
  { 18, -1, sizeof(::BasilMessage::BasilMessage)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::BasilMessage::_BasilMessage_PropertiesEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::BasilMessage::_BasilMessage_OpParametersEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::BasilMessage::_BasilMessage_default_instance_),
};

const char descriptor_table_protodef_BasilMessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022BasilMessage.proto\022\014BasilMessage\032\020Basi"
  "lTypes.proto\"\266\005\n\014BasilMessage\022\n\n\002op\030\001 \001("
  "\005\022,\n\004auth\030\002 \001(\0132\036.BasilType.AccessAuthor"
  "ization\022+\n\005class\030\016 \001(\0162\034.BasilMessage.Tr"
  "ansportClass\022-\n\010objectId\030\003 \001(\0132\033.BasilTy"
  "pe.ObjectIdentifier\0221\n\ninstanceId\030\004 \001(\0132"
  "\035.BasilType.InstanceIdentifier\022,\n\003pos\030\005 "
  "\001(\0132\037.BasilType.InstancePositionInfo\022.\n\t"
  "assetInfo\030\006 \001(\0132\033.BasilType.AssetInforma"
  "tion\022&\n\004aabb\030\007 \001(\0132\030.BasilType.AaBoundin"
  "gBox\022\016\n\006filter\030\010 \001(\t\022>\n\nproperties\030\t \003(\013"
  "2*.BasilMessage.BasilMessage.PropertiesE"
  "ntry\022B\n\014opParameters\030\n \003(\0132,.BasilMessag"
  "e.BasilMessage.OpParametersEntry\022,\n\texce"
  "ption\030\013 \001(\0132\031.BasilType.BasilException\022-"
  "\n\010response\030\r \001(\0132\033.BasilType.BResponseRe"
  "quest\0321\n\017PropertiesEntry\022\013\n\003key\030\001 \001(\t\022\r\n"
  "\005value\030\002 \001(\t:\0028\001\0323\n\021OpParametersEntry\022\013\n"
  "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001*_\n\016Transpo"
  "rtClass\022\013\n\007Default\020\000\022\020\n\014HighPriority\020\n\022\017"
  "\n\013MedPriority\020\024\022\017\n\013LowPriority\020\036\022\014\n\010Best"
  "Case\020(*\277\t\n\017BasilMessageOps\022\016\n\nUnknownReq"
  "\020\000\022!\n\034IdentifyDisplayableObjectReq\020\201 \022\"\n"
  "\035IdentifyDisplayableObjectResp\020\202 \022\037\n\032For"
  "getDisplayableObjectReq\020\203 \022 \n\033ForgetDisp"
  "layableObjectResp\020\204 \022\034\n\027CreateObjectInst"
  "anceReq\020\205 \022\035\n\030CreateObjectInstanceResp\020\206"
  " \022\034\n\027DeleteObjectInstanceReq\020\207 \022\035\n\030Delet"
  "eObjectInstanceResp\020\210 \022\034\n\027UpdateObjectPr"
  "opertyReq\020\211 \022\035\n\030UpdateObjectPropertyResp"
  "\020\212 \022\036\n\031UpdateInstancePropertyReq\020\213 \022\037\n\032U"
  "pdateInstancePropertyResp\020\214 \022\036\n\031UpdateIn"
  "stancePositionReq\020\215 \022\037\n\032UpdateInstancePo"
  "sitionResp\020\216 \022\037\n\032RequestObjectProperties"
  "Req\020\217 \022 \n\033RequestObjectPropertiesResp\020\220 "
  "\022!\n\034RequestInstancePropertiesReq\020\221 \022\"\n\035R"
  "equestInstancePropertiesResp\020\222 \022\024\n\017Close"
  "SessionReq\020\223 \022\025\n\020CloseSessionResp\020\224 \022\026\n\021"
  "MakeConnectionReq\020\225 \022\027\n\022MakeConnectionRe"
  "sp\020\226 \022\022\n\rAliveCheckReq\020\201@\022\023\n\016AliveCheckR"
  "esp\020\202@\022\023\n\016OpenSessionReq\020\201`\022\024\n\017OpenSessi"
  "onResp\020\202`\022\022\n\rCameraViewReq\020\203`\022\023\n\016CameraV"
  "iewResp\020\204`\022\026\n\020RegisterTopicReq\020\201\200\001\022\027\n\021Re"
  "gisterTopicResp\020\202\200\001\022\030\n\022DeregisterTopicRe"
  "q\020\203\200\001\022\031\n\023DeregisterTopicResp\020\204\200\001\022\022\n\014Subs"
  "cribeReq\020\205\200\001\022\023\n\rSubscribeResp\020\206\200\001\022\024\n\016Uns"
  "ubscribeReq\020\207\200\001\022\025\n\017UnsubscribeResp\020\210\200\001\022\022"
  "\n\014SendEventReq\020\211\200\001\022\023\n\rSendEventResp\020\220\200\001\022"
  "\016\n\010EventReq\020\221\200\001\022\017\n\tEventResp\020\222\200\001\022\031\n\023Subs"
  "criptionMadeReq\020\223\200\001\022\032\n\024SubscriptionMadeR"
  "esp\020\224\200\001\022\032\n\024SubscriptionClearReq\020\225\200\001\022\033\n\025S"
  "ubscriptionClearResp\020\226\200\001B&\252\002#org.herbal3"
  "d.basil.protocol.Messageb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_BasilMessage_2eproto_deps[1] = {
  &::descriptor_table_BasilTypes_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_BasilMessage_2eproto_sccs[3] = {
  &scc_info_BasilMessage_BasilMessage_2eproto.base,
  &scc_info_BasilMessage_OpParametersEntry_DoNotUse_BasilMessage_2eproto.base,
  &scc_info_BasilMessage_PropertiesEntry_DoNotUse_BasilMessage_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_BasilMessage_2eproto_once;
static bool descriptor_table_BasilMessage_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_BasilMessage_2eproto = {
  &descriptor_table_BasilMessage_2eproto_initialized, descriptor_table_protodef_BasilMessage_2eproto, "BasilMessage.proto", 2112,
  &descriptor_table_BasilMessage_2eproto_once, descriptor_table_BasilMessage_2eproto_sccs, descriptor_table_BasilMessage_2eproto_deps, 3, 1,
  schemas, file_default_instances, TableStruct_BasilMessage_2eproto::offsets,
  file_level_metadata_BasilMessage_2eproto, 3, file_level_enum_descriptors_BasilMessage_2eproto, file_level_service_descriptors_BasilMessage_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_BasilMessage_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_BasilMessage_2eproto), true);
namespace BasilMessage {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TransportClass_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_BasilMessage_2eproto);
  return file_level_enum_descriptors_BasilMessage_2eproto[0];
}
bool TransportClass_IsValid(int value) {
  switch (value) {
    case 0:
    case 10:
    case 20:
    case 30:
    case 40:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* BasilMessageOps_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_BasilMessage_2eproto);
  return file_level_enum_descriptors_BasilMessage_2eproto[1];
}
bool BasilMessageOps_IsValid(int value) {
  switch (value) {
    case 0:
    case 4097:
    case 4098:
    case 4099:
    case 4100:
    case 4101:
    case 4102:
    case 4103:
    case 4104:
    case 4105:
    case 4106:
    case 4107:
    case 4108:
    case 4109:
    case 4110:
    case 4111:
    case 4112:
    case 4113:
    case 4114:
    case 4115:
    case 4116:
    case 4117:
    case 4118:
    case 8193:
    case 8194:
    case 12289:
    case 12290:
    case 12291:
    case 12292:
    case 16385:
    case 16386:
    case 16387:
    case 16388:
    case 16389:
    case 16390:
    case 16391:
    case 16392:
    case 16393:
    case 16400:
    case 16401:
    case 16402:
    case 16403:
    case 16404:
    case 16405:
    case 16406:
      return true;
    default:
      return false;
  }
}


// ===================================================================

BasilMessage_PropertiesEntry_DoNotUse::BasilMessage_PropertiesEntry_DoNotUse() {}
BasilMessage_PropertiesEntry_DoNotUse::BasilMessage_PropertiesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void BasilMessage_PropertiesEntry_DoNotUse::MergeFrom(const BasilMessage_PropertiesEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata BasilMessage_PropertiesEntry_DoNotUse::GetMetadata() const {
  return GetMetadataStatic();
}
void BasilMessage_PropertiesEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::Message& other) {
  ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom(other);
}


// ===================================================================

BasilMessage_OpParametersEntry_DoNotUse::BasilMessage_OpParametersEntry_DoNotUse() {}
BasilMessage_OpParametersEntry_DoNotUse::BasilMessage_OpParametersEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void BasilMessage_OpParametersEntry_DoNotUse::MergeFrom(const BasilMessage_OpParametersEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata BasilMessage_OpParametersEntry_DoNotUse::GetMetadata() const {
  return GetMetadataStatic();
}
void BasilMessage_OpParametersEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::Message& other) {
  ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom(other);
}


// ===================================================================

void BasilMessage::InitAsDefaultInstance() {
  ::BasilMessage::_BasilMessage_default_instance_._instance.get_mutable()->auth_ = const_cast< ::BasilType::AccessAuthorization*>(
      ::BasilType::AccessAuthorization::internal_default_instance());
  ::BasilMessage::_BasilMessage_default_instance_._instance.get_mutable()->objectid_ = const_cast< ::BasilType::ObjectIdentifier*>(
      ::BasilType::ObjectIdentifier::internal_default_instance());
  ::BasilMessage::_BasilMessage_default_instance_._instance.get_mutable()->instanceid_ = const_cast< ::BasilType::InstanceIdentifier*>(
      ::BasilType::InstanceIdentifier::internal_default_instance());
  ::BasilMessage::_BasilMessage_default_instance_._instance.get_mutable()->pos_ = const_cast< ::BasilType::InstancePositionInfo*>(
      ::BasilType::InstancePositionInfo::internal_default_instance());
  ::BasilMessage::_BasilMessage_default_instance_._instance.get_mutable()->assetinfo_ = const_cast< ::BasilType::AssetInformation*>(
      ::BasilType::AssetInformation::internal_default_instance());
  ::BasilMessage::_BasilMessage_default_instance_._instance.get_mutable()->aabb_ = const_cast< ::BasilType::AaBoundingBox*>(
      ::BasilType::AaBoundingBox::internal_default_instance());
  ::BasilMessage::_BasilMessage_default_instance_._instance.get_mutable()->exception_ = const_cast< ::BasilType::BasilException*>(
      ::BasilType::BasilException::internal_default_instance());
  ::BasilMessage::_BasilMessage_default_instance_._instance.get_mutable()->response_ = const_cast< ::BasilType::BResponseRequest*>(
      ::BasilType::BResponseRequest::internal_default_instance());
}
class BasilMessage::HasBitSetters {
 public:
  static const ::BasilType::AccessAuthorization& auth(const BasilMessage* msg);
  static const ::BasilType::ObjectIdentifier& objectid(const BasilMessage* msg);
  static const ::BasilType::InstanceIdentifier& instanceid(const BasilMessage* msg);
  static const ::BasilType::InstancePositionInfo& pos(const BasilMessage* msg);
  static const ::BasilType::AssetInformation& assetinfo(const BasilMessage* msg);
  static const ::BasilType::AaBoundingBox& aabb(const BasilMessage* msg);
  static const ::BasilType::BasilException& exception(const BasilMessage* msg);
  static const ::BasilType::BResponseRequest& response(const BasilMessage* msg);
};

const ::BasilType::AccessAuthorization&
BasilMessage::HasBitSetters::auth(const BasilMessage* msg) {
  return *msg->auth_;
}
const ::BasilType::ObjectIdentifier&
BasilMessage::HasBitSetters::objectid(const BasilMessage* msg) {
  return *msg->objectid_;
}
const ::BasilType::InstanceIdentifier&
BasilMessage::HasBitSetters::instanceid(const BasilMessage* msg) {
  return *msg->instanceid_;
}
const ::BasilType::InstancePositionInfo&
BasilMessage::HasBitSetters::pos(const BasilMessage* msg) {
  return *msg->pos_;
}
const ::BasilType::AssetInformation&
BasilMessage::HasBitSetters::assetinfo(const BasilMessage* msg) {
  return *msg->assetinfo_;
}
const ::BasilType::AaBoundingBox&
BasilMessage::HasBitSetters::aabb(const BasilMessage* msg) {
  return *msg->aabb_;
}
const ::BasilType::BasilException&
BasilMessage::HasBitSetters::exception(const BasilMessage* msg) {
  return *msg->exception_;
}
const ::BasilType::BResponseRequest&
BasilMessage::HasBitSetters::response(const BasilMessage* msg) {
  return *msg->response_;
}
void BasilMessage::clear_auth() {
  if (GetArenaNoVirtual() == nullptr && auth_ != nullptr) {
    delete auth_;
  }
  auth_ = nullptr;
}
void BasilMessage::clear_objectid() {
  if (GetArenaNoVirtual() == nullptr && objectid_ != nullptr) {
    delete objectid_;
  }
  objectid_ = nullptr;
}
void BasilMessage::clear_instanceid() {
  if (GetArenaNoVirtual() == nullptr && instanceid_ != nullptr) {
    delete instanceid_;
  }
  instanceid_ = nullptr;
}
void BasilMessage::clear_pos() {
  if (GetArenaNoVirtual() == nullptr && pos_ != nullptr) {
    delete pos_;
  }
  pos_ = nullptr;
}
void BasilMessage::clear_assetinfo() {
  if (GetArenaNoVirtual() == nullptr && assetinfo_ != nullptr) {
    delete assetinfo_;
  }
  assetinfo_ = nullptr;
}
void BasilMessage::clear_aabb() {
  if (GetArenaNoVirtual() == nullptr && aabb_ != nullptr) {
    delete aabb_;
  }
  aabb_ = nullptr;
}
void BasilMessage::clear_exception() {
  if (GetArenaNoVirtual() == nullptr && exception_ != nullptr) {
    delete exception_;
  }
  exception_ = nullptr;
}
void BasilMessage::clear_response() {
  if (GetArenaNoVirtual() == nullptr && response_ != nullptr) {
    delete response_;
  }
  response_ = nullptr;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BasilMessage::kOpFieldNumber;
const int BasilMessage::kAuthFieldNumber;
const int BasilMessage::kClassFieldNumber;
const int BasilMessage::kObjectIdFieldNumber;
const int BasilMessage::kInstanceIdFieldNumber;
const int BasilMessage::kPosFieldNumber;
const int BasilMessage::kAssetInfoFieldNumber;
const int BasilMessage::kAabbFieldNumber;
const int BasilMessage::kFilterFieldNumber;
const int BasilMessage::kPropertiesFieldNumber;
const int BasilMessage::kOpParametersFieldNumber;
const int BasilMessage::kExceptionFieldNumber;
const int BasilMessage::kResponseFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BasilMessage::BasilMessage()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:BasilMessage.BasilMessage)
}
BasilMessage::BasilMessage(const BasilMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  properties_.MergeFrom(from.properties_);
  opparameters_.MergeFrom(from.opparameters_);
  filter_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from.filter().size() > 0) {
    filter_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.filter_);
  }
  if (from.has_auth()) {
    auth_ = new ::BasilType::AccessAuthorization(*from.auth_);
  } else {
    auth_ = nullptr;
  }
  if (from.has_objectid()) {
    objectid_ = new ::BasilType::ObjectIdentifier(*from.objectid_);
  } else {
    objectid_ = nullptr;
  }
  if (from.has_instanceid()) {
    instanceid_ = new ::BasilType::InstanceIdentifier(*from.instanceid_);
  } else {
    instanceid_ = nullptr;
  }
  if (from.has_pos()) {
    pos_ = new ::BasilType::InstancePositionInfo(*from.pos_);
  } else {
    pos_ = nullptr;
  }
  if (from.has_assetinfo()) {
    assetinfo_ = new ::BasilType::AssetInformation(*from.assetinfo_);
  } else {
    assetinfo_ = nullptr;
  }
  if (from.has_aabb()) {
    aabb_ = new ::BasilType::AaBoundingBox(*from.aabb_);
  } else {
    aabb_ = nullptr;
  }
  if (from.has_exception()) {
    exception_ = new ::BasilType::BasilException(*from.exception_);
  } else {
    exception_ = nullptr;
  }
  if (from.has_response()) {
    response_ = new ::BasilType::BResponseRequest(*from.response_);
  } else {
    response_ = nullptr;
  }
  ::memcpy(&op_, &from.op_,
    static_cast<size_t>(reinterpret_cast<char*>(&class__) -
    reinterpret_cast<char*>(&op_)) + sizeof(class__));
  // @@protoc_insertion_point(copy_constructor:BasilMessage.BasilMessage)
}

void BasilMessage::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_BasilMessage_BasilMessage_2eproto.base);
  filter_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&auth_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&class__) -
      reinterpret_cast<char*>(&auth_)) + sizeof(class__));
}

BasilMessage::~BasilMessage() {
  // @@protoc_insertion_point(destructor:BasilMessage.BasilMessage)
  SharedDtor();
}

void BasilMessage::SharedDtor() {
  filter_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete auth_;
  if (this != internal_default_instance()) delete objectid_;
  if (this != internal_default_instance()) delete instanceid_;
  if (this != internal_default_instance()) delete pos_;
  if (this != internal_default_instance()) delete assetinfo_;
  if (this != internal_default_instance()) delete aabb_;
  if (this != internal_default_instance()) delete exception_;
  if (this != internal_default_instance()) delete response_;
}

void BasilMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const BasilMessage& BasilMessage::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_BasilMessage_BasilMessage_2eproto.base);
  return *internal_default_instance();
}


void BasilMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:BasilMessage.BasilMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  properties_.Clear();
  opparameters_.Clear();
  filter_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == nullptr && auth_ != nullptr) {
    delete auth_;
  }
  auth_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && objectid_ != nullptr) {
    delete objectid_;
  }
  objectid_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && instanceid_ != nullptr) {
    delete instanceid_;
  }
  instanceid_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && pos_ != nullptr) {
    delete pos_;
  }
  pos_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && assetinfo_ != nullptr) {
    delete assetinfo_;
  }
  assetinfo_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && aabb_ != nullptr) {
    delete aabb_;
  }
  aabb_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && exception_ != nullptr) {
    delete exception_;
  }
  exception_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && response_ != nullptr) {
    delete response_;
  }
  response_ = nullptr;
  ::memset(&op_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&class__) -
      reinterpret_cast<char*>(&op_)) + sizeof(class__));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* BasilMessage::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 op = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          op_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .BasilType.AccessAuthorization auth = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(mutable_auth(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .BasilType.ObjectIdentifier objectId = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(mutable_objectid(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .BasilType.InstanceIdentifier instanceId = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(mutable_instanceid(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .BasilType.InstancePositionInfo pos = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(mutable_pos(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .BasilType.AssetInformation assetInfo = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ctx->ParseMessage(mutable_assetinfo(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .BasilType.AaBoundingBox aabb = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr = ctx->ParseMessage(mutable_aabb(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string filter = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParserUTF8(mutable_filter(), ptr, ctx, "BasilMessage.BasilMessage.filter");
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // map<string, string> properties = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&properties_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<::PROTOBUF_NAMESPACE_ID::uint8>(ptr) == 74);
        } else goto handle_unusual;
        continue;
      // map<string, string> opParameters = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&opparameters_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<::PROTOBUF_NAMESPACE_ID::uint8>(ptr) == 82);
        } else goto handle_unusual;
        continue;
      // .BasilType.BasilException exception = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 90)) {
          ptr = ctx->ParseMessage(mutable_exception(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .BasilType.BResponseRequest response = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 106)) {
          ptr = ctx->ParseMessage(mutable_response(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .BasilMessage.TransportClass class = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 112)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          set_class_(static_cast<::BasilMessage::TransportClass>(val));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool BasilMessage::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:BasilMessage.BasilMessage)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 op = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (8 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32>(
                 input, &op_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .BasilType.AccessAuthorization auth = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (18 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_auth()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .BasilType.ObjectIdentifier objectId = 3;
      case 3: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (26 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_objectid()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .BasilType.InstanceIdentifier instanceId = 4;
      case 4: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (34 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_instanceid()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .BasilType.InstancePositionInfo pos = 5;
      case 5: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (42 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_pos()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .BasilType.AssetInformation assetInfo = 6;
      case 6: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (50 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_assetinfo()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .BasilType.AaBoundingBox aabb = 7;
      case 7: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (58 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_aabb()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string filter = 8;
      case 8: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (66 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadString(
                input, this->mutable_filter()));
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
            this->filter().data(), static_cast<int>(this->filter().length()),
            ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE,
            "BasilMessage.BasilMessage.filter"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // map<string, string> properties = 9;
      case 9: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (74 & 0xFF)) {
          BasilMessage_PropertiesEntry_DoNotUse::Parser< ::PROTOBUF_NAMESPACE_ID::internal::MapField<
              BasilMessage_PropertiesEntry_DoNotUse,
              std::string, std::string,
              ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
              ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
              0 >,
            ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string > > parser(&properties_);
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE,
            "BasilMessage.BasilMessage.PropertiesEntry.key"));
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
            parser.value().data(), static_cast<int>(parser.value().length()),
            ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE,
            "BasilMessage.BasilMessage.PropertiesEntry.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // map<string, string> opParameters = 10;
      case 10: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (82 & 0xFF)) {
          BasilMessage_OpParametersEntry_DoNotUse::Parser< ::PROTOBUF_NAMESPACE_ID::internal::MapField<
              BasilMessage_OpParametersEntry_DoNotUse,
              std::string, std::string,
              ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
              ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
              0 >,
            ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string > > parser(&opparameters_);
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE,
            "BasilMessage.BasilMessage.OpParametersEntry.key"));
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
            parser.value().data(), static_cast<int>(parser.value().length()),
            ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE,
            "BasilMessage.BasilMessage.OpParametersEntry.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .BasilType.BasilException exception = 11;
      case 11: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (90 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_exception()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .BasilType.BResponseRequest response = 13;
      case 13: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (106 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_response()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .BasilMessage.TransportClass class = 14;
      case 14: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (112 & 0xFF)) {
          int value = 0;
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   int, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_class_(static_cast< ::BasilMessage::TransportClass >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:BasilMessage.BasilMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:BasilMessage.BasilMessage)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void BasilMessage::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:BasilMessage.BasilMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 op = 1;
  if (this->op() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32(1, this->op(), output);
  }

  // .BasilType.AccessAuthorization auth = 2;
  if (this->has_auth()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, HasBitSetters::auth(this), output);
  }

  // .BasilType.ObjectIdentifier objectId = 3;
  if (this->has_objectid()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, HasBitSetters::objectid(this), output);
  }

  // .BasilType.InstanceIdentifier instanceId = 4;
  if (this->has_instanceid()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, HasBitSetters::instanceid(this), output);
  }

  // .BasilType.InstancePositionInfo pos = 5;
  if (this->has_pos()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, HasBitSetters::pos(this), output);
  }

  // .BasilType.AssetInformation assetInfo = 6;
  if (this->has_assetinfo()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, HasBitSetters::assetinfo(this), output);
  }

  // .BasilType.AaBoundingBox aabb = 7;
  if (this->has_aabb()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, HasBitSetters::aabb(this), output);
  }

  // string filter = 8;
  if (this->filter().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->filter().data(), static_cast<int>(this->filter().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "BasilMessage.BasilMessage.filter");
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->filter(), output);
  }

  // map<string, string> properties = 9;
  if (!this->properties().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "BasilMessage.BasilMessage.PropertiesEntry.key");
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "BasilMessage.BasilMessage.PropertiesEntry.value");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->properties().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->properties().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->properties().begin();
          it != this->properties().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        BasilMessage_PropertiesEntry_DoNotUse::Funcs::SerializeToCodedStream(9, items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second, output);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->properties().begin();
          it != this->properties().end(); ++it) {
        BasilMessage_PropertiesEntry_DoNotUse::Funcs::SerializeToCodedStream(9, it->first, it->second, output);
        Utf8Check::Check(&(*it));
      }
    }
  }

  // map<string, string> opParameters = 10;
  if (!this->opparameters().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "BasilMessage.BasilMessage.OpParametersEntry.key");
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "BasilMessage.BasilMessage.OpParametersEntry.value");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->opparameters().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->opparameters().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->opparameters().begin();
          it != this->opparameters().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        BasilMessage_OpParametersEntry_DoNotUse::Funcs::SerializeToCodedStream(10, items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second, output);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->opparameters().begin();
          it != this->opparameters().end(); ++it) {
        BasilMessage_OpParametersEntry_DoNotUse::Funcs::SerializeToCodedStream(10, it->first, it->second, output);
        Utf8Check::Check(&(*it));
      }
    }
  }

  // .BasilType.BasilException exception = 11;
  if (this->has_exception()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, HasBitSetters::exception(this), output);
  }

  // .BasilType.BResponseRequest response = 13;
  if (this->has_response()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      13, HasBitSetters::response(this), output);
  }

  // .BasilMessage.TransportClass class = 14;
  if (this->class_() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnum(
      14, this->class_(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:BasilMessage.BasilMessage)
}

::PROTOBUF_NAMESPACE_ID::uint8* BasilMessage::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:BasilMessage.BasilMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 op = 1;
  if (this->op() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->op(), target);
  }

  // .BasilType.AccessAuthorization auth = 2;
  if (this->has_auth()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, HasBitSetters::auth(this), target);
  }

  // .BasilType.ObjectIdentifier objectId = 3;
  if (this->has_objectid()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, HasBitSetters::objectid(this), target);
  }

  // .BasilType.InstanceIdentifier instanceId = 4;
  if (this->has_instanceid()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, HasBitSetters::instanceid(this), target);
  }

  // .BasilType.InstancePositionInfo pos = 5;
  if (this->has_pos()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, HasBitSetters::pos(this), target);
  }

  // .BasilType.AssetInformation assetInfo = 6;
  if (this->has_assetinfo()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, HasBitSetters::assetinfo(this), target);
  }

  // .BasilType.AaBoundingBox aabb = 7;
  if (this->has_aabb()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        7, HasBitSetters::aabb(this), target);
  }

  // string filter = 8;
  if (this->filter().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->filter().data(), static_cast<int>(this->filter().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "BasilMessage.BasilMessage.filter");
    target =
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteStringToArray(
        8, this->filter(), target);
  }

  // map<string, string> properties = 9;
  if (!this->properties().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "BasilMessage.BasilMessage.PropertiesEntry.key");
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "BasilMessage.BasilMessage.PropertiesEntry.value");
      }
    };

    if (false &&
        this->properties().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->properties().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->properties().begin();
          it != this->properties().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = BasilMessage_PropertiesEntry_DoNotUse::Funcs::SerializeToArray(9, items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second, target);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->properties().begin();
          it != this->properties().end(); ++it) {
        target = BasilMessage_PropertiesEntry_DoNotUse::Funcs::SerializeToArray(9, it->first, it->second, target);
        Utf8Check::Check(&(*it));
      }
    }
  }

  // map<string, string> opParameters = 10;
  if (!this->opparameters().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "BasilMessage.BasilMessage.OpParametersEntry.key");
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "BasilMessage.BasilMessage.OpParametersEntry.value");
      }
    };

    if (false &&
        this->opparameters().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->opparameters().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->opparameters().begin();
          it != this->opparameters().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = BasilMessage_OpParametersEntry_DoNotUse::Funcs::SerializeToArray(10, items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second, target);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->opparameters().begin();
          it != this->opparameters().end(); ++it) {
        target = BasilMessage_OpParametersEntry_DoNotUse::Funcs::SerializeToArray(10, it->first, it->second, target);
        Utf8Check::Check(&(*it));
      }
    }
  }

  // .BasilType.BasilException exception = 11;
  if (this->has_exception()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        11, HasBitSetters::exception(this), target);
  }

  // .BasilType.BResponseRequest response = 13;
  if (this->has_response()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        13, HasBitSetters::response(this), target);
  }

  // .BasilMessage.TransportClass class = 14;
  if (this->class_() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      14, this->class_(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BasilMessage.BasilMessage)
  return target;
}

size_t BasilMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BasilMessage.BasilMessage)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, string> properties = 9;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->properties_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
      it = this->properties().begin();
      it != this->properties().end(); ++it) {
    total_size += BasilMessage_PropertiesEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // map<string, string> opParameters = 10;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->opparameters_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
      it = this->opparameters().begin();
      it != this->opparameters().end(); ++it) {
    total_size += BasilMessage_OpParametersEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // string filter = 8;
  if (this->filter().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->filter());
  }

  // .BasilType.AccessAuthorization auth = 2;
  if (this->has_auth()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *auth_);
  }

  // .BasilType.ObjectIdentifier objectId = 3;
  if (this->has_objectid()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *objectid_);
  }

  // .BasilType.InstanceIdentifier instanceId = 4;
  if (this->has_instanceid()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *instanceid_);
  }

  // .BasilType.InstancePositionInfo pos = 5;
  if (this->has_pos()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *pos_);
  }

  // .BasilType.AssetInformation assetInfo = 6;
  if (this->has_assetinfo()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *assetinfo_);
  }

  // .BasilType.AaBoundingBox aabb = 7;
  if (this->has_aabb()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *aabb_);
  }

  // .BasilType.BasilException exception = 11;
  if (this->has_exception()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *exception_);
  }

  // .BasilType.BResponseRequest response = 13;
  if (this->has_response()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *response_);
  }

  // int32 op = 1;
  if (this->op() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->op());
  }

  // .BasilMessage.TransportClass class = 14;
  if (this->class_() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->class_());
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BasilMessage::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:BasilMessage.BasilMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const BasilMessage* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<BasilMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:BasilMessage.BasilMessage)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:BasilMessage.BasilMessage)
    MergeFrom(*source);
  }
}

void BasilMessage::MergeFrom(const BasilMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:BasilMessage.BasilMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  properties_.MergeFrom(from.properties_);
  opparameters_.MergeFrom(from.opparameters_);
  if (from.filter().size() > 0) {

    filter_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.filter_);
  }
  if (from.has_auth()) {
    mutable_auth()->::BasilType::AccessAuthorization::MergeFrom(from.auth());
  }
  if (from.has_objectid()) {
    mutable_objectid()->::BasilType::ObjectIdentifier::MergeFrom(from.objectid());
  }
  if (from.has_instanceid()) {
    mutable_instanceid()->::BasilType::InstanceIdentifier::MergeFrom(from.instanceid());
  }
  if (from.has_pos()) {
    mutable_pos()->::BasilType::InstancePositionInfo::MergeFrom(from.pos());
  }
  if (from.has_assetinfo()) {
    mutable_assetinfo()->::BasilType::AssetInformation::MergeFrom(from.assetinfo());
  }
  if (from.has_aabb()) {
    mutable_aabb()->::BasilType::AaBoundingBox::MergeFrom(from.aabb());
  }
  if (from.has_exception()) {
    mutable_exception()->::BasilType::BasilException::MergeFrom(from.exception());
  }
  if (from.has_response()) {
    mutable_response()->::BasilType::BResponseRequest::MergeFrom(from.response());
  }
  if (from.op() != 0) {
    set_op(from.op());
  }
  if (from.class_() != 0) {
    set_class_(from.class_());
  }
}

void BasilMessage::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:BasilMessage.BasilMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BasilMessage::CopyFrom(const BasilMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BasilMessage.BasilMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BasilMessage::IsInitialized() const {
  return true;
}

void BasilMessage::Swap(BasilMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BasilMessage::InternalSwap(BasilMessage* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  properties_.Swap(&other->properties_);
  opparameters_.Swap(&other->opparameters_);
  filter_.Swap(&other->filter_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(auth_, other->auth_);
  swap(objectid_, other->objectid_);
  swap(instanceid_, other->instanceid_);
  swap(pos_, other->pos_);
  swap(assetinfo_, other->assetinfo_);
  swap(aabb_, other->aabb_);
  swap(exception_, other->exception_);
  swap(response_, other->response_);
  swap(op_, other->op_);
  swap(class__, other->class__);
}

::PROTOBUF_NAMESPACE_ID::Metadata BasilMessage::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace BasilMessage
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::BasilMessage::BasilMessage_PropertiesEntry_DoNotUse* Arena::CreateMaybeMessage< ::BasilMessage::BasilMessage_PropertiesEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateInternal< ::BasilMessage::BasilMessage_PropertiesEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::BasilMessage::BasilMessage_OpParametersEntry_DoNotUse* Arena::CreateMaybeMessage< ::BasilMessage::BasilMessage_OpParametersEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateInternal< ::BasilMessage::BasilMessage_OpParametersEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::BasilMessage::BasilMessage* Arena::CreateMaybeMessage< ::BasilMessage::BasilMessage >(Arena* arena) {
  return Arena::CreateInternal< ::BasilMessage::BasilMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
